<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <title>PHPMailer Test</title>
</head>
<body>
<div style="width: 640px; font-family: Arial, Helvetica, sans-serif; font-size: 11px;">
  <h1>Online Application Form</h1>
  <p>Notifications from Online Application Form</p>
  <p>Request Date <strong><?= $email ?></strong></p>
  <p>Please check your Information..</p><br />
  <a target='_blank' href='http://localhost/admission/appl_list.php'>http://localhost/admission/appl_list.php</a>
</div>
</body>
</html>